#!/bin/bash

# (1) Kill daemons, if running
sudo killall hostapd
sudo systemctl stop dnsmasq

# (2) Kill the WiFi connection daemon
sudo systemctl stop wpa-keepalive.service
sudo wpa_cli -i wlan0 terminate

# (3) Launch the access point
sudo service hostapd stop
sudo hostapd -B config/hostapd.conf

# (4) Configure an IPV4 subnet DHCP server
#sudo ifconfig wlan0 192.168.42.1
#sudo service udhcpd start

#echo "Creating Hotspot"
sudo ip link set dev wlan0 down
sudo ip a add 192.168.4.5/24 brd + dev wlan0
sudo ip link set dev wlan0 up
sudo dhcpcd -k wlan0 >/dev/null 2>&1
sudo systemctl start dnsmasq
#sudo systemctl start hostapd
